### PR TITLE
revert(android): revert change AndroidManifest to support RN < 0.71

### PR DESCRIPTION
**Pull request by MasonLe2497**
This PR revert AndroidManifest  file to add support RN 0.71

### CODE REVIEW

**Comment by MasonLe2497** [comment]
@mrousavy Hi, i create new PR for revert AndroidManifest change. Sorry about prev PR, when i sync code from master, something wrong so my change was discarded

**Comment by retyui** [comment]
@mrousavy what block you to make a release?

**Comment by mohamedadel1994825** [comment]
Hey mrousavy mean that if app have react-native version 0.64.0 it should be work ? @mrousavy

**Comment by doneill** [comment]
@mrousavy Confused by how this should work below RN < 0.71 as version [Release 2.6.0](https://github.com/mrousavy/react-native-mmkv/releases/tag/v2.6.0) min support level is 0.71+.  What version can be used with 0.69 #407?

**Pull request merged**
