### PR TITLE
Fix for Monorepo android build

### PR DESCRIPTION
**Pull request by andrewcorliss**
Fixes issue #178 

Adds global scope for Root Android Node Module Directory and Root Node Module Folder.
As well simplifies and cleans up strings.

### CODE REVIEW

**Comment by andrewcorliss** [comment]
Thanks

You are right I had missed updating the DNODE_MODULES_DIR path.  I had a different file I was using to test it locally.  Making a new push shortly.

Thanks @oblador

**Comment by mrousavy** [comment]
Cool, thank you for the PR! 🙏 

> still working towards a better solution. This is just a checkpoint

let me know when you want me to review (and merge) it!

**Comment by andrewcorliss** [comment]
This is now ready for Review 👍  

Thanks :)

**Comment by mrousavy** [comment]
Thanks!

**Pull request merged**
