### PR TITLE
MMKV now uses new SDK Version & Removing old gradle configuration 

### PR DESCRIPTION
**Pull request by SectionTN**
some commits have comment explains why i changed the following file.

### CODE REVIEW

**Comment by mrousavy** [comment]
Hi, thanks for your PR! Does this still build on older RN versions such as 0.65?

**Comment by SectionTN** [comment]
sorry but i haven't tested that, it builds normally on React Native 0.69.2 (on a big project)
can you please do it ? because I'm on a limited connection and MMKV will download Glog and Boost #426

**Comment by SectionTN** [comment]
it says your build tools ver 33 is corrupted, try reinstalling it again.

**Comment by SectionTN** [comment]
wait, i think the compileOptions line is required, since DX is no longer available on new build-tools versions

**Pull request closed without merging**
