### PR TITLE
feat: update MMKV submodule

### PR DESCRIPTION
**Pull request by tcK1**
Update MMKV Submodule to https://github.com/Tencent/MMKV/commit/b154a2387605646fcea07b1a2f36cbe8a6fc185a.

This should include the `1.3.9` release with a fix for https://github.com/mrousavy/react-native-mmkv/issues/707.

I'm not sure how to open a PR for version `2.12.2`, but if that's possible I can also help with it!

### CODE REVIEW

**Comment by mrousavy** [comment]
Awesome, LGTM thanks!

**Comment by DorianMazur** [comment]
@mrousavy Can you release new version with this fix? 🙏

**Comment by madhus1025** [comment]
@mrousavy Could you please release a new version 2.13.0 with above change, This also has 16KB support for Android 15.
Please let us know when can we expect this ?

**Comment by DorianMazur** [comment]
I can't wait for release, you can install new version like this:

```
"react-native-mmkv": "https://gitpkg.vercel.app/api/pkg.tgz?url=mrousavy/react-native-mmkv/package&commit=8b5e9d009c0e7da47d5bf4f3705b01f570f09c26",
```

cheers

**Comment by DorianMazur** [comment]
@madhus1025 You can use this version :) https://github.com/DorianMazur/react-native-mmkv/pkgs/npm/react-native-mmkv

**Comment by DorianMazur** [comment]
@madhus1025 You can use this:

```
"react-native-mmkv": "https://registry.npmjs.org/@mazurdorian/react-native-mmkv/-/react-native-mmkv-3.0.0-beta.7.tgz",
```

**Comment by madhus1025** [comment]
@DorianMazur  we are on react native old architecture, would this work ? Also our app is in production and using this might not be a viable option as this is in beta. Your thoughts ?

**Comment by DorianMazur** [comment]
@madhus1025 The current react-native-mmkv master branch only works with the new architecture. To make it compatible with the old setup, you need to fork the repo, create a branch from a commit or release before the beta was introduced, and apply your changes there.

**Comment by madhus1025** [comment]
@DorianMazur Thanks, i get this, but coming it from a release cadence is more cleaner right ? hence requesting for a new release.

**Comment by mendozammatias** [comment]
@madhus1025 I've created a version compatible with v2 so you can use it in projects without new architecture enabled:

```
"react-native-mmkv": "https://registry.npmjs.org/@mendozammatias/react-native-mmkv/-/react-native-mmkv-2.12.2.tgz"`
```

**Pull request merged**
