### PR TITLE
feat: added support for AGP>=8

### PR DESCRIPTION
**Pull request by AlirezaHadjar**
Added support for AGP version 8 and above to fix build issues on RN v0.73

### CODE REVIEW

**Comment by mrousavy** [comment]
Awesome, thanks! Let's see if the CI runs :)

**Comment by AlirezaHadjar** [comment]
@mrousavy I'm not sure what broke the lint report step. Do you have any idea how to fix it?

**Comment by mrousavy** [comment]
Hm, idk - I'm not sure if those artefacts are uploaded - can you try running those steps locally?

**Comment by AlirezaHadjar** [comment]
@mrousavy I think there's something wrong with the `Validate Android / Gradle Lint (pull_request)`. This issue also exists in many merged PRs: https://github.com/mrousavy/react-native-mmkv/pull/550 https://github.com/mrousavy/react-native-mmkv/pull/512 https://github.com/mrousavy/react-native-mmkv/pull/499 https://github.com/mrousavy/react-native-mmkv/pull/480. Apparently `Validate Android / Gradle Lint (pull_request)` always fails.

Let me know if I need to do anything 🙂

**Comment by mrousavy** [comment]
Okay yea true, I think then that CI is broken! Thanks, LGTM!

**Pull request merged**
