### PR TITLE
chore: add ios privacy manifest

### PR DESCRIPTION
**Pull request by RhyG**
Added a privacy manifest file to comply with Apple's upcoming [privacy manifest requirements](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files).

I based the reason and type off of Apple's docs for [describing use of required reason API](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api) and my understanding of what the library uses, but if it's not quite correct let me know and happy to adjust it.

### CODE REVIEW

**Comment by jbrodriguez** [comment]
the underlying library maintainer is removing uses of the apis that trigger the warning (he doesn't seem willing to include a privacy manifest in his library)

last change was made [2 days ago](https://github.com/Tencent/MMKV/issues/1220), i'm not sure if he cleaned up all instances of "offending" APIs, so it's probably a good idea to still declare the manifest here 🤷‍♂️ ? 

any thoughts @RhyG  ?

thanks for your work btw 👍

**Comment by mrousavy** [comment]
Hey - thanks for this PR, this is dope!

But I agree with @jbrodriguez - the maintainer of Tencent/MMKV is removing all the APIs that require such privacy manifests, and I think that's a better solution moving forward. See commits like https://github.com/Tencent/MMKV/commit/1feba14d3347050c181ab3e507ac8121d69ae656

**Review by calebmackdavenport — APPROVED** [review]

**Comment by mobileteo** [comment]
Any update on the release of this?

**Comment by cvisserMaxedy** [comment]
@mrousavy Could you check this PR? It's relatively simple. The alternative is that the manifest has to be set on the app level, which is a little dirty IMO.

**Comment by mrousavy** [comment]
> @mrousavy Could you check this PR? It's relatively simple. The alternative is that the manifest has to be set on the app level, which is a little dirty IMO.

Again, the real solution to this would be to upgrade the core MMKV library and remove all of the sensitive APIs.  You can already do that by just running pod update yourself.

In V3 I've already fixed this.

**Comment by RhyG** [comment]
In that case are you happy for me to close this @mrousavy?

**Comment by mrousavy** [comment]
yup thx

**Pull request closed without merging**
